%MATLAB Examples
%generateAudioPlugin audiopluginexample.BassEnhancer
%generateAudioPlugin audiopluginexample.Chorus
%generateAudioPlugin audiopluginexample.DampedVolumeController
%generateAudioPlugin audiopluginexample.Echo
%generateAudioPlugin audiopluginexample.Flanger
%generateAudioPlugin audiopluginexample.HighPassIIRFilter
%generateAudioPlugin audiopluginexample.ParametricEqualizer
%generateAudioPlugin audiopluginexample.ParametricEqualizerWithUDP
%generateAudioPlugin audiopluginexample.PitchShifter
%generateAudioPlugin audiopluginexample.ShelvingEqualizer
%generateAudioPlugin audiopluginexample.VarSlopeBandpassFilter

%Custom Plugins
generateAudioPlugin vstCompressorMono